version: '3'
services:
  nginx:
    image: nginx
    ports:
      - xxxx:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./www/html:/var/www/html
    networks:
      - frontend

  php:
    build: ./php
    volumes:
      - ./www/html:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - backend
      - frontend

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ....
      MYSQL_DATABASE: .....
      MYSQL_USER: ....
      MYSQL_PASSWORD: .......
    ports:
      - xxxx:3306
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - xxxx:80
    networks:
      - backend
  
networks:
  frontend:
  backend:
